language: node_js
node_js:
  - "0.12"
  - "4"
  - "5"
  - "6"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
env:
  global:
    - CI=true
  matrix:
    - TEST_DOC=false
    - TEST_DOC=true